import operator
from typing import Annotated, Any
from typing_extensions import TypedDict
from langgraph.graph import MessagesState
from langgraph.graph.message import add_messages


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # Each analyst owns an isolated message channel. Sharing MessagesState.messages
    # across parallel branches would mix unrelated tool calls and responses.
    market_messages: Annotated[list[Any], add_messages]
    social_messages: Annotated[list[Any], add_messages]
    news_messages: Annotated[list[Any], add_messages]
    fundamentals_messages: Annotated[list[Any], add_messages]
    policy_messages: Annotated[list[Any], add_messages]
    hot_money_messages: Annotated[list[Any], add_messages]
    lockup_messages: Annotated[list[Any], add_messages]

    analysis_mode: Annotated[str, "full or fast analysis mode"]
    selected_analysts: Annotated[list[str], "Analysts enabled for this run"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    policy_report: Annotated[str, "Report from the Policy Analyst (A-stock specific)"]
    hot_money_report: Annotated[str, "Report from the Hot Money Tracker (A-stock specific)"]
    lockup_report: Annotated[str, "Report from the Lockup/Reduction Watcher (A-stock specific)"]

    # data quality gate
    data_quality_summary: Annotated[str, "Quality gate assessment of all analyst reports (hard checks + LLM review)"]
    data_quality_status: Annotated[str, "Code-enforced confidence cap: 高/中/低"]
    data_quality_constraints: Annotated[
        str, "Binding claim restrictions derived from failed data domains"
    ]
    tool_execution_ledger: Annotated[
        list[dict[str, Any]], operator.add
    ]  # 每次工具调用的无敏感状态记录
    performance_ledger: Annotated[
        list[dict[str, Any]], operator.add
    ]  # 节点、模型和工具耗时；不含提示词、正文或网络地址
    performance_summary: Annotated[dict[str, Any], "Aggregated performance metrics"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
